### ISSUE TITLE
Create Hero

### ISSUE THREAD

**Issue by nicolaslechenic** [nicolaslechenic/mythique#5]
Create Hero methods to Characters module.

In first time Hero must have 
profile informations : firstname, lastname
character stats : HP, MP, current level
character actions : hit and health depends on character stats

**Comment by ldocao** [comment]
can we change HP to hit_points, and MP to magic_points ? Upper case variables are for constants.

**Comment by nicolaslechenic** [comment]
Of course it is only a description with ideas but you can do whatever you think necessary

**Comment by ldocao** [comment]
ennemy and hero class have been created. I still have to define action such as attack

**Comment by ldocao** [comment]
finished with normal attack (damned! forgot to add issue number in commit message...)
